/**
 * Smart Contract Utilities
 * Interaction with the eAkhuwat smart contract on-chain
 */

import { ethers } from "ethers";
import config from "../config";

// Minimal ABI for the eAkhuwat withdrawal contract
const CONTRACT_ABI = [
  "function withdraw(address recipient, uint256 amount, uint256 nonce, uint256 deadline, bytes signature) external",
  "function nonces(address user) external view returns (uint256)",
  "function paused() external view returns (bool)",
  "event Withdrawal(address indexed recipient, uint256 amount, uint256 nonce, bytes32 txHash)",
];

let provider: ethers.JsonRpcProvider | null = null;
let contract: ethers.Contract | null = null;
let signer: ethers.Wallet | null = null;

/**
 * Initialize the blockchain provider and contract
 */
export function initSmartContract(): void {
  if (!config.RPC_URL || config.RPC_URL.includes("YOUR_INFURA_KEY")) {
    console.warn("⚠️  Smart contract not initialized: RPC_URL not configured");
    return;
  }

  try {
    provider = new ethers.JsonRpcProvider(config.RPC_URL);

    if (config.SIGNER_PRIVATE_KEY) {
      signer = new ethers.Wallet(config.SIGNER_PRIVATE_KEY, provider);
      contract = new ethers.Contract(config.CONTRACT_ADDRESS, CONTRACT_ABI, signer);
    } else {
      contract = new ethers.Contract(config.CONTRACT_ADDRESS, CONTRACT_ABI, provider);
    }

    console.log("✅ Smart contract initialized:", config.CONTRACT_ADDRESS);
  } catch (err) {
    console.error("❌ Smart contract initialization failed:", err);
  }
}

/**
 * Get user's current on-chain nonce
 */
export async function getUserNonce(walletAddress: string): Promise<number> {
  if (!contract) {
    throw new Error("Smart contract not initialized");
  }

  try {
    const nonce = await contract.nonces(walletAddress);
    return Number(nonce);
  } catch (err) {
    throw new Error(`Failed to get nonce: ${err}`);
  }
}

/**
 * Check if contract is paused
 */
export async function isContractPaused(): Promise<boolean> {
  if (!contract) {
    return false;
  }

  try {
    return await contract.paused();
  } catch {
    return false;
  }
}

/**
 * Execute an on-chain withdrawal
 * The signature must be pre-generated by the server using EIP-712
 */
export async function executeWithdrawal(
  recipient: string,
  amountUsdc: number,
  nonce: number,
  deadline: number,
  signature: string
): Promise<{ txHash: string; blockNumber: number }> {
  if (!contract || !signer) {
    throw new Error("Smart contract or signer not initialized");
  }

  const paused = await isContractPaused();
  if (paused) {
    throw new Error("Contract is currently paused");
  }

  // Convert amount to 6 decimals (USDC)
  const amountWei = BigInt(Math.round(amountUsdc * 1_000_000));

  const tx = await contract.withdraw(recipient, amountWei, nonce, deadline, signature);
  const receipt = await tx.wait();

  return {
    txHash: receipt.hash,
    blockNumber: receipt.blockNumber,
  };
}

/**
 * Get the current block number
 */
export async function getCurrentBlock(): Promise<number> {
  if (!provider) {
    throw new Error("Provider not initialized");
  }
  return provider.getBlockNumber();
}

/**
 * Check if a transaction was confirmed on-chain
 */
export async function isTransactionConfirmed(txHash: string, requiredConfirmations = 1): Promise<boolean> {
  if (!provider) {
    return false;
  }

  try {
    const receipt = await provider.getTransactionReceipt(txHash);
    if (!receipt) return false;

    const currentBlock = await provider.getBlockNumber();
    const confirmations = currentBlock - receipt.blockNumber + 1;
    return confirmations >= requiredConfirmations;
  } catch {
    return false;
  }
}

/**
 * Get provider instance (for external use)
 */
export function getProvider(): ethers.JsonRpcProvider | null {
  return provider;
}

/**
 * Get contract instance (for external use)
 */
export function getContract(): ethers.Contract | null {
  return contract;
}
